[terminal]
vt = 1

[default_session]
command = "tuigreet --remember --remember-session --time --greeting 'Welcome back.' --theme 'border=green;text=white;prompt=yellow;time=gray;action=cyan;button=red;container=black;input=white' --sessions /usr/share/wayland-sessions"
user = "greetd"
